### PR TITLE
Create site skeleton

### PR DESCRIPTION
**Pull request by K02D**
## Changelog

### CODE REVIEW

**Comment by K02D** [comment]
image

This is how it looks like right now

**Comment by K02D** [comment]
image

This is how it looks like after all these commits. You can drag and select cells (and the time blocks of the cells are recorded when selected)

**Review by RosaGao — COMMENTED** [review]
The calendar looks great! Using schedule selector definitely makes it easy to specify the length of time slots and the starting/ending dates. Yet we would need to consider how to show different shades for different number of people. I guess we may calculate the shade based on how many people choose a particular cell and update the cell's selectedColor attribute? But I am not sure if this sets the color for all selected cells though.

**Comment by RosaGao** [comment]
I'm thinking would it be better if we borrow their implementations of selecting cells, recording selected times, etc (since it's published on gihub) and then build our skeleton upon that? of course given that we don't cause copyright issues

**Review by RosaGao — APPROVED** [review]
I'll start implementing the landing page over the break and let you know of any progress :)

**Pull request merged**
