### PR TITLE
implementing participantList functionality

### PR DESCRIPTION
**Pull request by RosaGao**
typeof Participants:
```
    id: number;
    name: string;
    timeSlots: string[];
```

subject to change

### CODE REVIEW

**Comment by RosaGao** [comment]
Just realized some type inconsistencies between front and back end. Will fix that shortly

**Comment by RosaGao** [comment]
image

I think we may use checked boxes to display the time slots of multiple members. Now when we toggle the boxes, the id's of members are saved. 

This feature is for the "Filter the availability by groups of people" user story.

**Comment by K02D** [comment]
Yes that looks good

**Comment by RosaGao** [comment]
image


I tried implementing the share button. Now when we click on share, it displays "Link copied" and the url is copied to the clipboard.

**Comment by K02D** [comment]
image

Each meeting now has a unique URL so you can now create different meetings and access each of them using by entering their unique URLs

**Comment by K02D** [comment]
There were a few merge conflicts when I was trying to commit and I may have undone some your changes by mistake Rosa. Really sorry about that if it happened :(

**Review by yesterd3v — APPROVED** [review]
LGTM

**Comment by yesterd3v** [comment]
@RosaGao @K02D Can either of you confirm if this is ready to merge? If it is, please go ahead and merge.

**Comment by K02D** [comment]
There are a few small issues here that I fixed on the calendar-rosa branch. I was wondering if we could close this PR without merging and continue working on calendar-rosa. We can maybe merge calendar-rosa once we have the calendar implemented, unless you want us to merge whatever is working now

**Comment by RosaGao** [comment]
@Boccca2014 We were updating both branches because the features are interdependent. So like Kiron said what is in this (participantList) branch is also in the calendar branch, and the calendar branch is more up-to-date.

**Comment by yesterd3v** [comment]
I see. I think if this is already merged into the `calendar-rosa` and this branch doesn't cause breaking changes (i.e. doesn't make the app worse), **it's fine to merge**. My understanding is that this will indirectly be merged anyway so might as well have the latest changes be reflected in `main.`

**Comment by RosaGao** [comment]
Thanks for the clarification! Kiron and I have been fixing/restoring merge issues because our last merge seemed to break both branches at that time. For now the `calendar-rosa` is running fine but the participantList branch is not (it might break things if merged). `calendar-rosa` has all the features in `participantList`, so would it be ok if we keep working on it and don't touch `participantList` just to be safe? 

I am rn working on showing different colors for selected cells and cells being selected, and hopefully will have progress made before this weekend. I know Kiron also mentioned features like hovering over cells to show overlapped selections etc. We will try making visible UI changes soon so that `main` could be updated. 

Thanks for your patience reading this long comment and hope this makes sense!

**Comment by yesterd3v** [comment]
Alright, please try to merge other branches ahead of creating new ones for future reference. The `root` to your branch should also always be stable to prevent errors from persisting.

**Comment by JJamesWWang** [comment]
Since the other branch has everything that this one does, we can close this. I would suggest trying to make your branches/PR changes smaller - one change/feature = 1 PR; this makes it so that you can add things in incremental changes.

In this case, since other features had to be implemented before the participant list, this should have been started/branched after those features were completed, otherwise you have to worry about keeping the branches in sync with each other (which is a reasonable strategy, but in your case not really necessary since there's only two of you). In other words, try to keep your progress linear and avoiding branching off unless necessary or it's beneficial (you are both working on completely separate features with little chance of interfering with each other's changes).

**Pull request closed without merging**
